### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by syptic** [doraemon127/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
- [x] All relevant code examples written with backticks (```)
- [x] All screenshots correspond to the described steps
- [x] All titles of sections are formatted as headers or similar
- [x] Lab report is on its own page, not the index page
- [ ] Last example counts keystrokes and shows how to run remotely saving time
  - Missing example and keystroke counts for it.
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:
Great job overall, loved the style and formatting!

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page
```

**Comment by aammya8** [comment]
Hello,
Thank you for the feedback! I wanted to clarify, for the checkbox that I'm missing, I should add another screenshot right (with one specific example that I list keystroke counts for)? Also, just to double check, total keystroke count includes everything right (letters, punctuation, arrow keys, enter key, etc.)?
Thank you! :D

**Comment by syptic** [comment]
Yeah, that sounds good!

**Comment by aammya8** [comment]
Hello,
I just submitted a regrade request on gradescope. Here's a screenshot of my improvements for reference, thank you!

<img width="810" alt="Screen Shot 2022-01-27 at 11 58 24 AM" src="https://user-images.githubusercontent.com/79061216/151434814-f03164ae-5ce0-4836-bd9f-109e762f5b81.png">
